### ISSUE TITLE
can't find libpd-ios.a

### ISSUE THREAD

**Issue by brandonpon96** [libpd/libpd#101]
I can't seem to figure out where this library is located...how did you guys get this library?

**Comment by danomatika** [comment]
You need to build it using the libpd.xcodeproj Xcode project file.

One way to add it to your project is to drag it into your current Xcode project, then make sure to add the libpd-ios library to your Linked Frameworks and Libraries in the General tab of your project target.

**Comment by brandonpon96** [comment]
Is it supposed to be red?  I have it linked in my project, but I have a feeling that the file itself doesn't exist on my computer.  I click in xcode to go to file location, and all it does is open up finder.  I dont see the library file in the git repository either.  In xcode, libpd-ios.a is in a folder called "Products", along with libpd-osx.a, both of which are red.  I can't find this folder outside of xcode.

**Comment by danomatika** [comment]
That's not a problem, it's just red because it has't been built yet. You don;t have to find the file itself because Xcode will handle it. 

Sounds like you need to read into how Static Libraries work with in Xcode, see http://www.raywenderlich.com/41377/creating-a-static-library-in-ios-tutorial. ".a" files are statically compiled libraries that are then linked into app when you build it. It's basically a compiled file of all the libpd source code.

**Comment by brandonpon96** [comment]
Ok I see!  Yes this is my first time working with static libraries in Xcode, didn't know you had to build the library beforehand.  Thanks!

**Comment by danomatika** [comment]
No problem. Providing the static lib Xcode project *assumes* a bit about experience level. I'll add a note in the readme.
