### ISSUE TITLE
OS X Python install - can't find portaudio.h

### ISSUE THREAD

**Issue by nyboer** [libpd/libpd#106]
I kept having the problem when running 
`easy_install pyaudio`
that `portaudio.h` was not found. It has to do with how Homebrew installs portaudio.
Installing portaudio with brew puts it in the directory:
`/usr/local/Cellar/portaudio/19.20140130`
So I moved it:
```
cd /usr/local/Cellar/portaudio/
cp -r 19.20140130/ portaudio
mv portaudio/ /usr/local/lib
```
Then I did
`easy_install pyaudio`
which gave me some reassuring output:
```
Searching for pyaudio
Best match: PyAudio 0.2.8
Adding PyAudio 0.2.8 to easy-install.pth file
Using /Library/Python/2.7/site-packages
Processing dependencies for pyaudio
Finished processing dependencies for pyaudio
```
I then went to the python/ directory and ran make which generated a LOT of warnings, but seemed to work, more or less. Then I finished with sudo make install which was fine. 
I still have some figuring out to do, since the examples didn't really work right (though they did produce glitchy sound). But at least it built!

**Comment by RolandMetivier** [comment]
Doing this command works too if you got PortAudio installed with Homebrew

`pip3 install pyaudio --global-option="build_ext" --global-option="-I/usr/local/include" --global-option="-L/usr/local/lib"`

**Comment by danomatika** [comment]
Building with libraries installed by Homebrew should always use the `/usr/local/include` and `/usr/local/lib` paths. Homebrew installs most things to it's "Cellar" but then symlinks to both of these for libraries.

Glad y'all got it to work. Closing as this is a Homebrew/Python issue and not directly related libpd.

**Comment by isathish** [comment]
I am facing issue 👍 
$ pip3 install pyaudio --global-option="build_ext" --global-option="-I/usr/local/include" --global-option="-L/usr/local/lib"
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/commands/install.py:194: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Collecting pyaudio
  Using cached PyAudio-0.2.11.tar.gz
Installing collected packages: pyaudio
  Running setup.py install for pyaudio ... error
    Complete output from command /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/rm/55wh8hks0dg3tbzpmc2p5p7m0000gp/T/pip-build-mcw6e0ek/pyaudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" build_ext -I/usr/local/include -L/usr/local/lib install --record /var/folders/rm/55wh8hks0dg3tbzpmc2p5p7m0000gp/T/pip-pyq9r60d-record/install-record.txt --single-version-externally-managed --compile:
    running build_ext
    building '_portaudio' extension
    creating build
    creating build/temp.macosx-10.6-intel-3.6
    creating build/temp.macosx-10.6-intel-3.6/src
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -DMACOSX=1 -I/usr/local/include -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c src/_portaudiomodule.c -o build/temp.macosx-10.6-intel-3.6/src/_portaudiomodule.o
    src/_portaudiomodule.c:29:10: fatal error: 'portaudio.h' file not found
    #include "portaudio.h"
             ^~~~~~~~~~~~~
    1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1
    
    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/rm/55wh8hks0dg3tbzpmc2p5p7m0000gp/T/pip-build-mcw6e0ek/pyaudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" build_ext -I/usr/local/include -L/usr/local/lib install --record /var/folders/rm/55wh8hks0dg3tbzpmc2p5p7m0000gp/T/pip-pyq9r60d-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/rm/55wh8hks0dg3tbzpmc2p5p7m0000gp/T/pip-build-mcw6e0ek/pyaudio/

**Comment by tromgy** [comment]
If you're on macOS and see this error, you need to install **portaudio** library first. Run (using Homebrew)

```
brew install portaudio
```

and then install **pyaudio** with pip.

**Comment by danomatika** [comment]
@tromgy Should we add this clarification to the readme somewhere?

**Comment by tromgy** [comment]
sure, I think it's a good idea.

**Comment by danomatika** [comment]
Ok, added via commit: https://github.com/libpd/libpd/commit/5748c477c1ed1d135d680935dca9016a9de45c37

**Comment by saad-uddin** [comment]
Hi I am still facing this issue 

`pip3 install pyaudio --global-option="build_ext" --global-option="-I/usr/local/include" --global-option="-L/usr/local/lib"                                                 ✔  12:22:01
WARNING: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
Defaulting to user installation because normal site-packages is not writeable
Collecting pyaudio
  Using cached PyAudio-0.2.12.tar.gz (42 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pyaudio
  Building wheel for pyaudio (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pyaudio (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-universal2-cpython-310
      copying src/pyaudio.py -> build/lib.macosx-10.9-universal2-cpython-310
      running build_ext
      building '_portaudio' extension
      creating build/temp.macosx-10.9-universal2-cpython-310
      creating build/temp.macosx-10.9-universal2-cpython-310/src
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -DMACOSX=1 -I/usr/local/include -I/usr/include -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c src/_portaudiomodule.c -o build/temp.macosx-10.9-universal2-cpython-310/src/_portaudiomodule.o
      src/_portaudiomodule.c:31:10: fatal error: 'portaudio.h' file not found
      #include "portaudio.h"
               ^~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyaudio
Failed to build pyaudio
ERROR: Could not build wheels for pyaudio, which is required to install pyproject.toml-based projects`
