### ISSUE TITLE
Can't build on OSX 10.11

### ISSUE THREAD

**Issue by Mviljamaa** [libpd/libpd#120]
Tried building libpd using the supplied libpd.xcodeproj. Trying to build this leads to:

![screen shot 2016-02-13 at 00 01 37](https://cloud.githubusercontent.com/assets/1913544/13021656/ff1e0080-d1e4-11e5-8408-d0c19769c319.png)

Then tried building using the included Makefile:

```
> make
make: *** No rule to make target `pure-data/src/d_arithmetic.o', needed by `libs/libpd.dylib'.  Stop.
```

**Comment by danomatika** [comment]
This is not helpful at all. Again, we have no idea as to what steps you took to set up the Xcode project or how you are calling make.

Just because *you* maybe be having trouble building libpd doesn't mean libpd itself is broken. If you have general questions about building C libraries, etc I'd suggest starting on the pd list and or pd forum. We use the Github issue system for tracking bugs and features ideas, not as a general help.

For instance, did you follow the [instructions in the main readme that requires you to checkout the pure-data source file submodule](https://github.com/libpd/libpd#pure-data)? If you haven't done that, your `libpd/pure-data` folder will be empty and you will be missing the files you need to build libpd.

**Comment by Mviljamaa** [comment]
I edited the question to be more clear, perhaps.

**Comment by Mviljamaa** [comment]
Also what does this mean:

> git://git.code.sf.net/p/pure-data/pure-data

If you're cloning this repo, make sure to checkout the submodule:

git submodule init
git submodule update

**Comment by danomatika** [comment]
>Why aren't all the instructions here:

Because it's assumed people using the Github page know how to clone source code from Github. See https://linuxprograms.wordpress.com/2010/10/26/checkout-code-from-github

The zip download, however, is an issue because Github doesn't include the submodule files in the zip. So you may have downloaded libpd but the pure-data folder is empty. I'll add a note about that.

The preferred method is to use git to clone the repo, do not use the zip:

    git clone https://github.com/libpd/libpd.git
    git submodule init
    git submodule update

The pure-data folder contains the pd source code itself. Everything else are the wrappers that make up libpd.

**Comment by Mviljamaa** [comment]
Ok so I did the cloning using git and the compilation succeeds using the .xcodeproj.

**Comment by Mviljamaa** [comment]
However, I don't see where it put the build.

**Comment by danomatika** [comment]
Xcode static libraries automatically link to your project. You do not work with the lib file itself as Xcode handles everything for you. This is different than working with Makefiles.

**Comment by Mviljamaa** [comment]
So it didn't generate a .dylib/.so, but rather modified the /libpd/ folder somehow?
And now I include the lib by dragging the .xcodeproj into some project?

**Comment by danomatika** [comment]
Well, I wrote a wiki page this morning that explains how to add libpd.xcodeproj to your own custom Xcode project: https://github.com/libpd/libpd/wiki/libpd

It's literally drag and drop + adding the header search paths. This is common for using any static lib project in Xcode, not just libpd.

For further questions, please read the Xcode documentation on using static Xcode library projects.

**Comment by Mviljamaa** [comment]
It says that static libraries are .a files, but I don't see the build created such.

**Comment by Mviljamaa** [comment]
Ok so I followed the instructions here:
https://github.com/libpd/libpd/wiki/Working-with-libpd-in-Xcode#add

The build fails.

**Comment by Mviljamaa** [comment]
You forgot to mention in the above link that the entire libpd.xcodeproj must be that which resides in the libpd folder. I.e. it has to have a reference to that folder. I followed the instructions and copied ONLY the libpd.xcodeproj file to my project folder, and it didn't compile. Then I copied the entire libpd folder into MyProject/libpd/ (where the .xcodeproj also was) and now it compiles.
