### ISSUE TITLE
C++ integration

### ISSUE THREAD

**Issue by Skalbeard** [libpd/libpd#150]
I have a Visual Studio 2015 project that I am trying to integrate PD in.
What I did:
1) cloned this repo.
2) went through all the documentation points and the wiki pages. Installed mingw, msys and all the whatnot shit that I don't really understand as all they seemed to do was try to overwrite something that already exists.
3) I also tried downloading and integrating the NuGet PD package which I also had to hack around to set it up in the first place and it still didn't f-ing work.
4) I have created a local /lib and /include folder in my project where I have put the libwinpthread-1.dll and the /libpd/cpp contents accordingly. As far as my experience goes with linking in projects, I should not be able to build my project with everything included if it was set up wrong in the project. Meaning that I only get the error when I actually try and instantiate my PDController object. It finds the includes and the classes.
I am not a linux user and I don't understand where does the documentation assume that I am one and where it does not. I also don't understand what it is that I have to build or not to build as the repo already has folders with cpp includes and the lib folders with the libwinpthread-1.dll files that the setup claims to build. Do I have to build the whole Pure Data advanced binary as a runnable software? I already have it downloaded and working. Do I have to rebuild the .dll? (Why? As it already is there.) None of all of this crap works straight out of the box. I've went over the sample code, found the Open Framework, various sources that tried integrating into visual studio and haven't succeeded and dug up the entire internet for this. I've went over the documentation and all the steps like three times and I am slightly f-ing annoyed. I hope it's something really stupid that I've forgotten or missed. Any help would be appreciated.
That's the error:

> BaseApplication.obj : error LNK2019: unresolved external symbol "public: __thiscall pd::PdBase::PdBase(void)" (??0PdBase@pd@@QAE@XZ) referenced in function "public: __thiscall PDController::PDController(void)" (??0PDController@@QAE@XZ)

**Comment by danomatika** [comment]
(Removing duplicate post in #86 so I can respond here.)

> I have a Visual Studio 2015 project that I am trying to integrate PD in.

As #86 points out, libpd doesn't currently build in Visual Studio C++.

> What I did:
> 1) cloned this repo.
> 2) went through all the documentation points and the wiki pages. Installed mingw, msys and all the whatnot shit that I don't really understand as all they seemed to do was try to overwrite something that already exists.

mingw & msys are environments to provide a Unix/Linux shell environment with the gcc & autotools build systems, for which libpd does build on Windows. Going this route, you'd build a libpd .dll and then link it in your app. If you're not familiar with the open source toolchains, there is plenty of information online.

> 3) I also tried downloading and integrating the NuGet PD package which I also had to hack around to set it up in the first place and it still didn't f-ing work.

As far as I can tell, not having a Windows box in front of me, the libpd NuGet package is for C#, not C++. 

> 4) I have created a local /lib and /include folder in my project where I have put the libwinpthread-1.dll and the /libpd/cpp contents accordingly. As far as my experience goes with linking in projects, I should not be able to build my project with everything included if it was set up wrong in the project. Meaning that I only get the error when I actually try and instantiate my PDController object. It finds the includes and the classes.

I'm a little confused. There is no "PDController" in the C++ wrapper. Are you referring to the C# wrapper?

> I am not a linux user and I don't understand where does the documentation assume that I am one and where it does not.

Fair point. Overall, this project comes from a gcc/makefile background which assumes some experience with open source software tools.

> I also don't understand what it is that I have to build or not to build as the repo already has folders with cpp includes and the lib folders with the libwinpthread-1.dll files that the setup claims to build. Do I have to build the whole Pure Data advanced binary as a runnable software?

libpd is generally used in two ways:

1. as a dynamic library you can link in your application
2. by building the sources directly within your application

For option 1, we provide:

* the makefile which builds the libpd:
  * core C library
  * core C lib + C++ wrapper
  * core C lib + C# wrapper
  * core C lib + Java wrapper
* two batch files to build libpd for C# in mingw
* a setup.py to build the Python wrapper
* a libpd Xcode project which builds libpd and the Obj-C wrapper for iOS & OS X

For option 2, you're a bit more on your own. Easiest method is to look inside makefile to see the list of files that are compiled to build libpd.

> I already have it downloaded and working. Do I have to rebuild the .dll? (Why? As it already is there.)

What is downloaded & working? If you have a .dll, you should be able to link to it and include the headers in `/cpp`, `/libpd_wrapper`, & `/pure-data/src`.

> None of all of this crap works straight out of the box.

Sorry. Again, libpd doesn't currently support Visual Studio C/C++. It may be some simple fixes, but we'll need a Windows dev to pitch in and check it out. The we'll need to communicate the required changes upstream to the main pure-data developers as libpd wraps the core of pure-data itself.

The C# wrapper is built using the pd.dll built using mingw.

Conversely, libpd is built n the gcc/makefile toolchain using:

    cd libpd
    make 

> I've went over the sample code, found the Open Framework, various sources that tried integrating into visual studio and haven't succeeded and dug up the entire internet for this.

By "Open Framework", do you mean "openFrameworks" the C++ creative coding toolkit? ofxPd, the oF addon that uses libpd [does not support VS either](https://github.com/danomatika/ofxPd#windows). I've went over the documentation and all the steps like three times and I am slightly f-ing annoyed. I hope it's something really stupid that I've forgotten or missed.

Well, the "entire internet" kind of boils down to #86 which pretty much states other people haven't been able to get it to work yet. I know you didn't miss it since you made a duplicate post there...

> Any help would be appreciated.

Tip: ranting, then asking for help generally doesn't encourage help.

**Comment by Skalbeard** [comment]
I apologize. I had spent the unhealthy part of the night banging my head against this. Thank you for the comprehensive and swift response.
The PDController that I am mentioning is my own class that encapsulates the integration. So when I include and link everything, it seems to be working, as in it recognises the namespace and scope and all.
What I have downloaded and working is the Pure Data software as a standalone.
And by openframework I mean the one you mention, yes.
So am I supposed to be able to use the winpthread-1.dll? Is it the right one or am I supposed to find a way to build the C lib + C++ wrapper from the makefile and is there some kind of LibPD.dll that should be generated? I went through the files in the make file and I did not find anything that isn't already in the repo.

**Comment by danomatika** [comment]
> So am I supposed to be able to use the winpthread-1.dll? Is it the right one or am I supposed to find a way to build the C lib + C++ wrapper from the makefile and is there some kind of LibPD.dll that should be generated? I went through the files in the make file and I did not find anything that isn't already in the repo.

It depends on how you want do use libpd.

Option 1:

If you are trying to include the source files into your project manually, you will need to link to pthreads. The current setup relies on MinGW for Windows and I believe MinGW includes the pthread.h header, so you may need to find a copy of that as well. [winpthread](https://sourceware.org/pthreads-win32/) is a wrapper layer for the [POSIX pthread library](https://en.wikipedia.org/wiki/POSIX_Threads) used to port software written for Unix/Linux/BSD to use the Windows thread API. It's relatively common requirement for open source projects.

My suggestion of looking in the makefile was that it lists all the files included with libpd that are required to build libpd. Thus, if you are grabbing just those files needed to build libpd and building them directly in your project, the makefile is a handy list of which files you need. If you also want the C++ wrapper, then throw in the files in `/cpp`.

As noted in #86, though, there are still some issues with this, so I'd recommend Option 2. It will *not* work out of the box yet.

Option 2:

Using MinGW, you can build a pd.dll. Then, you can use this dll in your application and should only need to include the relevant headers, as mentioned in the last post. Building libpd via the makefile is covered in the libpd readme. The nutshell is, using the MinGW shell environment (msys I believe), you run the following in the libpd directory:

    make cpplib EXTRA=true

That will build the libpd C core, the C++ wrapper, and the extra externals ([bonk~], [fiddle~], etc) into a dll.
