### ISSUE TITLE
Adjust Pure Data scene graph on the fly without patch reload

### ISSUE THREAD

**Issue by kylestew** [libpd/libpd#173]
Is it possible to add/remove/edit elements in the scene graph on the fly through libpd? I believed I've exhaustively searched through all sample code and apps the have shipped for mobile. 

Basically I'm looking into making a simple Pure Data editor for iOS and then Android. 

It looks like even PdParty only parses the file and then maps the active libpd patch to GUI elements.

Any insight would be appreciated!

**Comment by danomatika** [comment]
**Nutshell**

Yes, this would be be nice but we as a community need to work out the best way to do it.

**Long Answer**

There is no built in way to access/manipulate the DSP graph. We would like to work towards abstracting it but it is a non-trivial task. I would look into the discussions on the pd lists and into Jonathan Wilkes work on Purr Data in this area and it is something we could probably add in the future but may involve changes to the Pd core.

> It looks like even PdParty only parses the file and then maps the active libpd patch to GUI elements.

Yes because I decided I didn't want to work for at least a year (for free) on a custom implementation when all I really need to do was to *use* patches on the device, not create them. I *may* only ever add editing *if* we as a community come up with a generative abstraction layer for the DSP graph (as you suggest). I *do not* want to reinvent the wheel...

**Comment by kylestew** [comment]
Thanks for the response @danomatika, glad to know I hadn't missed something. Also, thanks for keeping PdParty open source, it has been a great resource as I've been digging into Pure Data on mobile.

I'm going to go ahead and close this thread and stick with the desktop version of PD for a bit while I continue to map out my idea. Basically I'm focusing on Pure Data as a toolset for embedded systems, pretty much extending the idea over at http://bela.io/. Not sure yet if mobile, web, or desktop software is the way to go yet.

**Comment by danomatika** [comment]
Definitely bring this up again on pd-list as it's something that would very useful in the long run. It's just not a quick slam dunk right now :)

_Also, I'm entirely convinced the desktop patching metaphor can be translated to mobile without some interaction design reworking..._
