### ISSUE TITLE
“Semantic issue: Implicitly declaring library function 'malloc' with type 'void *(unsigned long)'”

### ISSUE THREAD

**Issue by Dassine** [libpd/libpd#192]
Many files contains this error : “Semantic issue: Implicitly declaring library function 'malloc' with type 'void *(unsigned long)'” 

The solution is to add : #include <stdlib.h>

https://stackoverflow.com/questions/28666441/semantic-issue-implicitly-declaring-library-function-malloc-with-type-void

**Comment by danomatika** [comment]
We need more information. How are you building libpd? On/for what system? etc

Also, note that it's suggested in the readme to use the latest stable release tag and not the current master.

EDIT: Also, is this an error you're seeing or a warning?

**Comment by Dassine** [comment]
I added libpd pod in oct 2015. this error showed up since the last XCode update. This an error that prevent me to compile my project.

**Comment by danomatika** [comment]
Try removing s_file.c form your project and recompiling.

**Comment by danomatika** [comment]
Note: This is essentially fixed in the current master branch, but there needs to be some work and testing before a new release which probably won't happen until a couple weeks from now.

In the meantime, you can just manually add the include to `s_file.c` in your project to compile. In the next version, libpd no longer builds this file so this issue does not occur.

**Comment by danomatika** [comment]
This is more or less fixed in the current master.
