### ISSUE TITLE
pdtest_thread crashes on libpd_free_instance()

### ISSUE THREAD

**Issue by danomatika** [libpd/libpd#271]
In keeping with this thread (https://github.com/pure-data/pure-data/issues/727), I have updated libpd to pd 0.50-2 sources and replaced calling `sys_microsleep()` with `sys_pollgui()`. Most of the samples are running fine, however `c/pdtest_thread` is crashing due to a double free when it calls `libpd_free_instance` on the last thread.

@pierreguillot Can you check this out?

**Comment by danomatika** [comment]
@pierreguillot Have you had a check this? I'd like to have it fixed for the 0.12 release soonish...

**Comment by pierreguillot** [comment]
I'm really sorry about this very long delay... 

I think `sys_pollgui()` should also be used https://github.com/libpd/libpd/blob/master/libpd_wrapper/z_libpd.c#L215.

I'm still investigating the libpd_free_instance() problem...

**Comment by danomatika** [comment]
Yeah, please create PRs.

**Comment by danomatika** [comment]
It seems to be working with the current libpd `master` branch. The output I'm seeing now is:
~~~
pd 0.51.2
bonk version 1.5
fiddle version 1.1 TEST4
pique 0.1 for PD version 23
sigmund~ version 0.07
1003-frequency: loadbang
1003-frequency: loadbang
1003-frequency: loadbang
1003-frequency: loadbang
~~~

**Comment by pierreguillot** [comment]
It seems that this issue requires another fix. This is related to Pd so feel free to tell me if you think I should create an issue in the Pd repository. 

The problem was not really (or entirely) fixed by PR but the problem seems to occur when deleting/managing the classes in `pdinstance_free()` (https://github.com/pure-data/pure-data/blob/master/src/m_class.c#L213-L223). 

The problem seems due to the fact that [instanceno](https://github.com/pure-data/pure-data/blob/master/src/m_class.c#L201) is not thread-safe. In a multi-thread/instance context, if `pdinstance_free()` is called concurrently the value can be invalid due to (pdinstance_renumber())[https://github.com/pure-data/pure-data/blob/master/src/m_class.c#L151]. Initializing the value after the [locks](https://github.com/pure-data/pure-data/blob/master/src/m_class.c#L207) seems to fix the problem. Here is a [patch.zip](https://github.com/libpd/libpd/files/5505292/fix-pdinstance_free.patch.zip). I'm going to create a PR on Pd.

I guess this is the only place where `instanceno` can create problems but an extra look by someone else would be useful!

**Comment by danomatika** [comment]
I'll reopen this for now then.

**Comment by danomatika** [comment]
This is working with Pd 0.50-3. Thanks for the help.
