### ISSUE TITLE
libpd_symbol() during libpd_openfile() causes deadlock

### ISSUE THREAD

**Issue by giuliomoro** [libpd/libpd#274]
Say that you have a patch like:

```
[loadbang]
|
[send me a symbol(
|
[s toWrapper]

[r fromWrapper]
|
[print]
```

and that the registered messagehook tries to send a message such as `libpd_symbol("fromWrapper", "symbol")`, then as you load the patch with `libpd_openfile()`, you'll end up in a deadlock situation. This is because `libpd_openfile()` calls `sys_lock()` before loading the patch, but also `libpd_symbol()` wants to lock the lock. And so, if in response to the `[loadbang]` triggered by `libpd_openfile()`, a call is performed to `libpd_symbol()`, then there you have this deadlock situation.

**Comment by giuliomoro** [comment]
same for `libpd_arraysize()` etc

**Comment by danomatika** [comment]
@Spacechild1 Should we use sys_trylock here?

**Comment by Spacechild1** [comment]
I just had a quick look at the libpd wrapper code. Seems like most methods are internally protected by `sys_lock/sys_unlock`. `sys_trylock` doesn't really help, because what shall we do we if can't grab the lock?

What we actually need is a recursive mutex, e.g. something like `sys_lockshared/sys_unlockshared`. This can be done by combining `sys_lock/sys_unlock` with a thread local counter:

```
static PERTHREAD int sys_lockcount;

void sys_lockshared()
{
    if (!sys_lockcount++)
        sys_lock();
}

void sys_unlockshared()
{
    if (!--sys_lockcount)
        sys_unlock();
}
```

This should do the trick.

**Comment by danomatika** [comment]
Ok. Do you think we can just add this to the libpd side or does the core need similar changes?

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by Spacechild1** [comment]
This can be entirely done on the libpd side, but it wouldn't hurt if we also had this in the core :-) I've been bitten by the non-recursive `sys_lock` in the past... so I might do a PR to Pd.

**Comment by Spacechild1** [comment]
I can also make a PR to libpd, of course.

**Comment by danomatika** [comment]
I will also look into something related: per-instance receive hooks ala #204

**Comment by danomatika** [comment]
I've made an initial implementation of @Spacechild1's suggestion in the `bugfix/shared-lock` branch. I made a patch confirming your findings and this seems to fix it. Please test.

**Comment by giuliomoro** [comment]
thanks! Incidentally, what is the lock locking against?

**Comment by danomatika** [comment]
The audio thread, mainly. We know that is a sin nowadays with lockless audio being preferred, but odd architecture is older and it may take alot of work to refactor for that.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by giuliomoro** [comment]
but ... it's supposed to be single threaded, no?
I see you recently updated the wiki turning 

```
-Note:   `m_pd.h` does offer global locking with `sys_lock` and `sys_unlock`, but I don't see how to safely use them.  They use one non-reentrant global lock, and it doesn't seem to be clear who is responsible for it.  In other words, `sys_lock` and `sys_unlock` seem like a recipe for deadlocks.  I recommend using your own private lock.
```

into

```
+As of version 0.11.0, the base libpd itself is thread-safe through the usage of Pd global lock mechanism and instance-specific data is declared "per thread."
```

In what way is it thread-safe now? Can messages be sent from other threads without `libpd_queued`?

**Comment by danomatika** [comment]
Yes. Miller added locking to the C api, so it is, more or less, thread safe. I don't use the queue in PdParty, for instance.

**Comment by danomatika** [comment]
>but ... it's supposed to be single threaded, no?

It depends on what you mean by "single-threaded."

All live-audio applications are at the minimum working with two threads: main/GUI and audio threads. This is why Pd has an internal locking mechanism. That's the "old way of doing it," but it works. The "new way" is to use ring buffers for everything, including message sending to separate these parts and avoid locking as much as possible.

On the pd-list, most users think "single-threaded" because the main messaging and object chain architecture is determinant, aka things happen in a specific order on the same "thread" conceptually. "Multi-threaded" Pd would be those objects which do processing in the background on different threads this removing some aspects of their messaging from the determinate "main thread."

**Comment by Spacechild1** [comment]
> It may be partially wrong.

I think that's pretty on point.

> The "new way" is to use ring buffers for everything

libpd already offers this for *receiving* messages (z_queued.h) and it could also offer it for *sending* messages.

**Comment by danomatika** [comment]
As far as I can tell using pdtest & a test patch, this is fixed in the current master.
