### ISSUE TITLE
naming of .dll / .so file

### ISSUE THREAD

**Issue by mxa** [libpd/libpd#297]
Maybe a detail, but the final build product is called `libpd.so` on linux, but on windows it's called `pd.dll`. shouldn't that be `libpd.dll `for consistency?

**Comment by Spacechild1** [comment]
This is on purpose, because on Windows, Pd externals implicitly link against `pd.dll` and expect this DLL to be present. On Linux and macOS the situation is different because Pd externals just auto import the symbols and don't care whether they come from a `pd` executable or a `libpd.so` shared library.

**Comment by mxa** [comment]
I see. For an [older project](https://github.com/LibPdIntegration/LibPdIntegration/tree/master/Assets/Plugins/x64) which used a `libpd.dll` and doesn't have any externals, can I just rename it to `libpd.dll`?

**Comment by Spacechild1** [comment]
> can I just rename it to libpd.dll?

this should actually work.

**Comment by danomatika** [comment]
Ideally it would be "libpd.dll" but it was originally "pd.dll" so all preexisting externals expect this.

One thing to note: If you want to use externals with libpd, then you should use "pd.dll." This will work as long as libpd is built with dynamic loading enabled.
