### ISSUE TITLE
Multiple instance library networking errors macOS

### ISSUE THREAD

**Issue by gorborukov** [libpd/libpd#304]
I use libpd in C++ Juce project (macOS Catalina 10.15.4) and everything is fine with default libpd, but if I use libpd with multiple instance support instead, I can’t build the project due to errors regarding Pd networking (please look at the screenshot). Just in case, I don’t need Pd networking features in my project. I built both libpd-osx.a and libpd-osx-multi.a from the master branch. I also noticed that the compiled files have a very different size: 6.6 mb for libpd-osx and 3.8 mb for multiple instance version. Is there any way to use multiple instance library without these Pd networking related errors?

![Снимок экрана 2020-07-05 в 02 38 09](https://user-images.githubusercontent.com/2666067/86522799-ba9f4680-be6b-11ea-9394-7371177ca39b.png)

**Comment by Spacechild1** [comment]
Hi, this has nothing to do with multiinstance support. `s_inter.o` and `x_net.o` are referencing functions which are only available in Pd 0.51, but libpd is currently still at Pd 0.50-2.

Please cd into the `pure-data` subdirectory and verify that HEAD is at https://github.com/pure-data/pure-data/commit/d8d637b6c53833c49c47c60ff78e3fbfd0d596c7 (= the 0.50-2 tag)

HEAD must *not* be at master, because it contains new files (`s_net.c`) which are not included in the libpd build system (yet).

**Comment by Spacechild1** [comment]
see also https://github.com/libpd/libpd/pull/299

**Comment by gorborukov** [comment]
> Hi, this has nothing to do with multiinstance support. `s_inter.o` and `x_net.o` are referencing functions which are only available in Pd 0.51, but libpd is currently still at Pd 0.50-2.
> 
> Please cd into the `pure-data` subdirectory and verify that HEAD is at [pure-data/pure-data@d8d637b](https://github.com/pure-data/pure-data/commit/d8d637b6c53833c49c47c60ff78e3fbfd0d596c7) (= the 0.50-2 tag)
> 
> HEAD must _not_ be at master, because it contains a new file (`s_net.c`) that is not included in the libpd build system (yet).

Hi, I checked and really I had the wrong pure-data HEAD. Now the project is built without errors, thanks!
