### ISSUE TITLE
subpatch Graph-On-Parent, how to send value

### ISSUE THREAD

**Issue by tomasyk** [libpd/libpd#305]
Is there any way how to send float value using libpd to subpatch Hslider _period_ in mainrotor subpatch (Graph-On-Parent) ?
Sending _$0-distance_ and other from main patch are working correctly, but for mainrotor, I am unable to send the value. I have tried _period_, _$0-period_, _$0-mainrotor-period_, _mainrotor-period_, no one is working. I think I need to get $0 for this subpatch, but is there any way how to obtain it?
![pic1](https://user-images.githubusercontent.com/50111214/86583571-cc740d00-bf83-11ea-8a69-25431e437e18.png)
![pic2](https://user-images.githubusercontent.com/50111214/86583573-cd0ca380-bf83-11ea-8a7b-5c40e5a96015.png)

**Comment by Spacechild1** [comment]
Well, first of all in the Hslider properties I don't see a receive symbol... so I'm not surprised you can't send any values.

$0 is meant as a mechanism to make variables *local*, i.e. to prevent making them publicly accessible. If you need public access to a variable, simply don't use $0.

In your case, the abstraction "mainrotor" could either have inlet(s) where you can send messages to set each slider, or the abstraction could take a creation argument which is prepent to each receive symbol, e.g. `/mainrotor/$1/period`. If you create the abstraction as `[mainrotor 0]`, you can then set the period from anywhere with `/mainrotor/0/period`. This is how many modular Pd toolkits are built.

Of course, you could just use `/mainrotor/period`, but this gets you in trouble once you need more than 1 instance of an abstraction. It's better to always use some kind of namespacing.

BTW, since this is really a patching question, it would be better suited for the Pd mailing list, forum or Facebook group.

**Comment by tomasyk** [comment]
Thank you, thats exactly what I have now realised, that sending is not working to sliders, but because of "r $0-name". I have already put inlet to mainrotor and it is working. Thank you again.
