### ISSUE TITLE
No audio playing from pdtest

### ISSUE THREAD

**Issue by trurohawkins** [libpd/libpd#373]
Hey I am running Arch Linux with the xterm-256 terminal.
I followed the guide and installed libpd for core C using the Makefile.
I am trying to run the basic samples for c, I can compile and run pdtest and pdtest_double just fine, but no sound comes out, are they supposed to play some audio? If so how do I get this to work, is there somewhere I can tell libpd to look in a different location for my sound drivers or something like that? Some flag or something to set, how does libpd connect to my sound drivers?

**Comment by danomatika** [comment]
The C core library does not come with any sound interfacing code since this is platform-specific. Both examples you cite are tests and only process samples in/out using dummy bummers. For actual sound I/O you need to use an audio library for your platform (ALSA) or a cross-platform wrapper (RtAudio, Portaudio, etc) then feed sound samples in/out of libpd using one of the process functions.

There is a C++ example which uses RtAudio and another which uses Jack.

Also, note that *some* language wrappers include audio handling, such as Obj-C and it's iOS AudioUnit, however this is platform-specific.

**Comment by danomatika** [comment]
Since you are using C, I would suggest using Portaudio. You can basically open input and output streams to the default devices then have libpd process samples form the input to the output. The buffer size needs to be a multipel Pd's block size of 64, so 128. 256, 512, etc.

At this point we should probably have a small sample/test which uses portaudio and C...

**Comment by danomatika** [comment]
Ok, pull latest master. There is now a pdtest_portaudio C sample: https://github.com/libpd/libpd/tree/master/samples/c/pdtest_portaudio

On Linux, you will need to install the dev version of portaudio with your distorts package manager. After that, build via `make` should work. Run with `./pdtest_portaudio test.pd .` or name & dir to any patch really. The sample runs the patch for 10 seconds using the default input and output audio devices.

**Comment by trurohawkins** [comment]
awesome thank you very much, this explains a lot!
