### ISSUE TITLE
[Discussion] should we add a ringbuffer to send messages from the host code to libpd?

### ISSUE THREAD

**Issue by rvega** [libpd/libpd#67]
Hi, I was testing the code discussed in 
https://github.com/libpd/libpd/commit/9c21f62d57f010bb868a357ebd8a0423158b3e31 and I noticed that sending a large amount of messages from the host code to libpd, with PdBase::sendFloat, for example, causes audio buffer underruns. 
This is because there is no ringbuffer in place for host to libpd communication and locks are used.

Is it worth the hassle to implement ringbuffer communication for this use-case? I can take a stab at it but I can move to more useful tasks if someone else´s experience shows this is not really needed for musical apps.

My use case is to create GUIs in QT for PD patches running in libpd in the same QT app.

Cheers!

**Comment by danomatika** [comment]
Ok, it's in master now. I revisited the cpp-queued branch and cleaned it up. I basically added an argument to PdBase::init() which allows you to conditionally enable the queued message passing. Otherwise, you still have the LIBPD_USE_STD_MUTEX option. This offers the most flexibility I think. I also removed the old message passing interface since it's redundant now.
